version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "${APP_PORT}:80"
      - "${APP_PORT_SSL}:443"
    volumes:
      - ./docker/site.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    links:
      - php
    depends_on:
      - php
    restart: unless-stopped

  php:
    hostname: php
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    volumes:
      - ./docker/wookteam.conf:/etc/supervisor/conf.d/wookteam.conf
      - ./docker/log/supervisor:/var/log/supervisor
      - ./:/var/www
    environment:
      TZ: "Asia/Shanghai"
    links:
      - mariadb
    depends_on:
      - mariadb

  mariadb:
    hostname: mariadb
    image: "bitnami/mariadb"
    user: root
    volumes:
      - ./docker/mariadb:/bitnami/mariadb
    environment:
      - "MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
      - "MARIADB_DATABASE=${DB_DATABASE}"
      - "MARIADB_USER=${DB_USERNAME}"
      - "MARIADB_PASSWORD=${DB_PASSWORD}"
    restart: always
